language: ruby

dist: trusty

matrix:
  include:
    - rvm: 2.1
    - rvm: 2.2
    - rvm: 2.3.3
    - rvm: 2.4.0
    - rvm: ruby-head
    - rvm: jruby-head
      before_install:
        - gem install bundler
    - rvm: jruby-9.1.14.0

script:
  - rake

env:
  global:
    - JRUBY_OPTS="--debug"
